[versions]
guava = "33.0.0-jre"
junit-jupiter = "5.10.2"
picocli = "4.6.1"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
